# Generated by Django 4.0.2 on 2022-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficbotapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Do', models.CharField(max_length=300)),
                ('dont', models.CharField(max_length=300)),
            ],
        ),
    ]
